import { Inter } from "next/font/google";
import "./globals.css";
import { SettingsSection } from "@/components/settingsSection/SettingsSection";
import { MainSection } from "@/components/mainSection/MainSection";
import InfoSection from "@/components/infoSection/InfoSection";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
                <div className="container">
                    <div className="wrapper">
                        <SettingsSection />
                        <MainSection />
                        <InfoSection />
                    </div>
                </div>
            </body>
        </html>
    );
}
